export default {
	enum: {
		['gogoproto.goproto_enum_prefix']: { type: 'bool', field: 62001 },
		['gogoproto.goproto_enum_stringer']: { type: 'bool', field: 62021 },
		['gogoproto.enum_stringer']: { type: 'bool', field: 62022 },
		['gogoproto.enum_customname']: { type: 'string', field: 62023 },
		['gogoproto.enumdecl']: { type: 'bool', field: 62024 }
	},
	enumValue: {
		['gogoproto.enumvalue_customname']: { type: 'string', field: 66001 }
	},
	file: {
		['gogoproto.goproto_getters_all']: { type: 'bool', field: 63001 },
		['gogoproto.goproto_enum_prefix_all']: { type: 'bool', field: 63002 },
		['gogoproto.goproto_stringer_all']: { type: 'bool', field: 63003 },
		['gogoproto.verbose_equal_all']: { type: 'bool', field: 63004 },
		['gogoproto.face_all']: { type: 'bool', field: 63005 },
		['gogoproto.gostring_all']: { type: 'bool', field: 63006 },
		['gogoproto.populate_all']: { type: 'bool', field: 63007 },
		['gogoproto.stringer_all']: { type: 'bool', field: 63008 },
		['gogoproto.onlyone_all']: { type: 'bool', field: 63009 },
		['gogoproto.equal_all']: { type: 'bool', field: 63013 },
		['gogoproto.description_all']: { type: 'bool', field: 63014 },
		['gogoproto.testgen_all']: { type: 'bool', field: 63015 },
		['gogoproto.benchgen_all']: { type: 'bool', field: 63016 },
		['gogoproto.marshaler_all']: { type: 'bool', field: 63017 },
		['gogoproto.unmarshaler_all']: { type: 'bool', field: 63018 },
		['gogoproto.stable_marshaler_all']: { type: 'bool', field: 63019 },
		['gogoproto.sizer_all']: { type: 'bool', field: 63020 },
		['gogoproto.goproto_enum_stringer_all']: { type: 'bool', field: 63021 },
		['gogoproto.enum_stringer_all']: { type: 'bool', field: 63022 },
		['gogoproto.unsafe_marshaler_all']: { type: 'bool', field: 63023 },
		['gogoproto.unsafe_unmarshaler_all']: { type: 'bool', field: 63024 },
		['gogoproto.goproto_extensions_map_all']: { type: 'bool', field: 63025 },
		['gogoproto.goproto_unrecognized_all']: { type: 'bool', field: 63026 },
		['gogoproto.gogoproto_import']: { type: 'bool', field: 63027 },
		['gogoproto.protosizer_all']: { type: 'bool', field: 63028 },
		['gogoproto.compare_all']: { type: 'bool', field: 63029 },
		['gogoproto.typedecl_all']: { type: 'bool', field: 63030 },
		['gogoproto.enumdecl_all']: { type: 'bool', field: 63031 },
		['gogoproto.goproto_registration']: { type: 'bool', field: 63032 },
		['gogoproto.messagename_all']: { type: 'bool', field: 63033 },
		['gogoproto.goproto_sizecache_all']: { type: 'bool', field: 63034 },
		['gogoproto.goproto_unkeyed_all']: { type: 'bool', field: 63035 }
	},
	message: {
		['gogoproto.goproto_getters']: { type: 'bool', field: 64001 },
		['gogoproto.goproto_stringer']: { type: 'bool', field: 64003 },
		['gogoproto.verbose_equal']: { type: 'bool', field: 64004 },
		['gogoproto.face']: { type: 'bool', field: 64005 },
		['gogoproto.gostring']: { type: 'bool', field: 64006 },
		['gogoproto.populate']: { type: 'bool', field: 64007 },
		['gogoproto.stringer']: { type: 'bool', field: 67008 },
		['gogoproto.onlyone']: { type: 'bool', field: 64009 },
		['gogoproto.equal']: { type: 'bool', field: 64013 },
		['gogoproto.description']: { type: 'bool', field: 64014 },
		['gogoproto.testgen']: { type: 'bool', field: 64015 },
		['gogoproto.benchgen']: { type: 'bool', field: 64016 },
		['gogoproto.marshaler']: { type: 'bool', field: 64017 },
		['gogoproto.unmarshaler']: { type: 'bool', field: 64018 },
		['gogoproto.stable_marshaler']: { type: 'bool', field: 64019 },
		['gogoproto.sizer']: { type: 'bool', field: 64020 },
		['gogoproto.goproto_extensions_map']: { type: 'bool', field: 64025 },
		['gogoproto.goproto_unrecognized']: { type: 'bool', field: 64026 },
		['gogoproto.protosizer']: { type: 'bool', field: 64028 },
		['gogoproto.compare']: { type: 'bool', field: 64029 },
		['gogoproto.typedecl']: { type: 'bool', field: 64030 },
		['gogoproto.messagename']: { type: 'bool', field: 64033 },
		['gogoproto.goproto_sizecache']: { type: 'bool', field: 64034 },
		['gogoproto.goproto_unkeyed']: { type: 'bool', field: 64035 }
	},
	field: {
		['gogoproto.nullable']: { type: 'bool', field: 65001 },
		['gogoproto.embed']: { type: 'bool', field: 65002 },
		['gogoproto.customtype']: { type: 'string', field: 65003 },
		['gogoproto.customname']: { type: 'string', field: 65004 },
		['gogoproto.jsontag']: { type: 'string', field: 65005 },
		['gogoproto.moretags']: { type: 'string', field: 65006 },
		['gogoproto.casttype']: { type: 'string', field: 65007 },
		['gogoproto.castkey']: { type: 'string', field: 65008 },
		['gogoproto.castvalue']: { type: 'string', field: 65009 },
		['gogoproto.stdtime']: { type: 'bool', field: 65010 },
		['gogoproto.stdduration']: { type: 'bool', field: 65011 },
		['gogoproto.wktpointer']: { type: 'bool', field: 65012 },
		['gogoproto.castrepeated']: { type: 'string', field: 65013 }
	}
};
