export default {
	enum: {
		goproto_enum_prefix: { type: 'bool', field: 62001 },
		goproto_enum_stringer: { type: 'bool', field: 62021 },
		enum_stringer: { type: 'bool', field: 62022 },
		enum_customname: { type: 'string', field: 62023 },
		enumdecl: { type: 'bool', field: 62024 }
	},
	enumValue: {
		enumvalue_customname: { type: 'string', field: 66001 }
	},
	file: {
		goproto_getters_all: { type: 'bool', field: 63001 },
		goproto_enum_prefix_all: { type: 'bool', field: 63002 },
		goproto_stringer_all: { type: 'bool', field: 63003 },
		verbose_equal_all: { type: 'bool', field: 63004 },
		face_all: { type: 'bool', field: 63005 },
		gostring_all: { type: 'bool', field: 63006 },
		populate_all: { type: 'bool', field: 63007 },
		stringer_all: { type: 'bool', field: 63008 },
		onlyone_all: { type: 'bool', field: 63009 },
		equal_all: { type: 'bool', field: 63013 },
		description_all: { type: 'bool', field: 63014 },
		testgen_all: { type: 'bool', field: 63015 },
		benchgen_all: { type: 'bool', field: 63016 },
		marshaler_all: { type: 'bool', field: 63017 },
		unmarshaler_all: { type: 'bool', field: 63018 },
		stable_marshaler_all: { type: 'bool', field: 63019 },
		sizer_all: { type: 'bool', field: 63020 },
		goproto_enum_stringer_all: { type: 'bool', field: 63021 },
		enum_stringer_all: { type: 'bool', field: 63022 },
		unsafe_marshaler_all: { type: 'bool', field: 63023 },
		unsafe_unmarshaler_all: { type: 'bool', field: 63024 },
		goproto_extensions_map_all: { type: 'bool', field: 63025 },
		goproto_unrecognized_all: { type: 'bool', field: 63026 },
		gogoproto_import: { type: 'bool', field: 63027 },
		protosizer_all: { type: 'bool', field: 63028 },
		compare_all: { type: 'bool', field: 63029 },
		typedecl_all: { type: 'bool', field: 63030 },
		enumdecl_all: { type: 'bool', field: 63031 },
		goproto_registration: { type: 'bool', field: 63032 },
		messagename_all: { type: 'bool', field: 63033 },
		goproto_sizecache_all: { type: 'bool', field: 63034 },
		goproto_unkeyed_all: { type: 'bool', field: 63035 }
	},
	message: {
		goproto_getters: { type: 'bool', field: 64001 },
		goproto_stringer: { type: 'bool', field: 64003 },
		verbose_equal: { type: 'bool', field: 64004 },
		face: { type: 'bool', field: 64005 },
		gostring: { type: 'bool', field: 64006 },
		populate: { type: 'bool', field: 64007 },
		stringer: { type: 'bool', field: 67008 },
		onlyone: { type: 'bool', field: 64009 },
		equal: { type: 'bool', field: 64013 },
		description: { type: 'bool', field: 64014 },
		testgen: { type: 'bool', field: 64015 },
		benchgen: { type: 'bool', field: 64016 },
		marshaler: { type: 'bool', field: 64017 },
		unmarshaler: { type: 'bool', field: 64018 },
		stable_marshaler: { type: 'bool', field: 64019 },
		sizer: { type: 'bool', field: 64020 },
		goproto_extensions_map: { type: 'bool', field: 64025 },
		goproto_unrecognized: { type: 'bool', field: 64026 },
		protosizer: { type: 'bool', field: 64028 },
		compare: { type: 'bool', field: 64029 },
		typedecl: { type: 'bool', field: 64030 },
		messagename: { type: 'bool', field: 64033 },
		goproto_sizecache: { type: 'bool', field: 64034 },
		goproto_unkeyed: { type: 'bool', field: 64035 }
	},
	field: {
		nullable: { type: 'bool', field: 65001 },
		embed: { type: 'bool', field: 65002 },
		customtype: { type: 'string', field: 65003 },
		customname: { type: 'string', field: 65004 },
		jsontag: { type: 'string', field: 65005 },
		moretags: { type: 'string', field: 65006 },
		casttype: { type: 'string', field: 65007 },
		castkey: { type: 'string', field: 65008 },
		castvalue: { type: 'string', field: 65009 },
		stdtime: { type: 'bool', field: 65010 },
		stdduration: { type: 'bool', field: 65011 },
		wktpointer: { type: 'bool', field: 65012 },
		castrepeated: { type: 'string', field: 65013 }
	}
};
